/// 단어 데이터 모델
///
/// 퀴즈에 사용될 단어 정보를 담는 클래스입니다.
class Word {
  final String? id; // New field for Firebase document ID
  final String word;
  final String meaning;
  final String category;
  final String difficulty;
  final String? hint;
  final String? imageUrl;

  Word({
    this.id, // Optional ID parameter
    required this.word,
    required this.meaning,
    required this.category,
    required this.difficulty,
    this.hint,
    this.imageUrl,
  });

  // Updated fromMap to include id
  factory Word.fromMap(Map<String, dynamic> map) {
    return Word(
      id: map['id'],
      word: map['word'],
      meaning: map['meaning'],
      hint: map['hint'],
      category: map['category'],
      difficulty: map['difficulty'],
      imageUrl: map['imageUrl'],
    );
  }

  // Updated toMap to include id
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'word': word,
      'meaning': meaning,
      'hint': hint,
      'category': category,
      'difficulty': difficulty,
      'imageUrl': imageUrl,
    };
  }

  // Updated fromFirestore to also capture document ID
  factory Word.fromFirestore(Map<String, dynamic> data, String documentId) {
    return Word(
      id: documentId,
      word: data['word'] ?? '',
      meaning: data['meaning'] ?? '',
      category: data['category'] ?? '',
      difficulty: data['difficulty'] ?? '보통',
      hint: data['hint'],
      imageUrl: data['imageUrl'],
    );
  }

  // Exclude ID from toFirestore as Firebase handles document IDs separately
  Map<String, dynamic> toFirestore() {
    return {
      'word': word,
      'meaning': meaning,
      'category': category,
      'difficulty': difficulty,
      'hint': hint,
      'imageUrl': imageUrl,
    };
  }
}

/// 기본 단어 목록
///
/// 앱에서 사용할 기본 단어 데이터 목록입니다.
/// 나중에는 데이터베이스나 API에서 가져올 수 있습니다.
final List<Word> allWords = [
  Word(
    word: 'airplane',
    meaning: '비행기',
    hint: '하늘을 날아다니는 탈것이에요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'ambulance',
    meaning: '구급차',
    hint: '아픈 사람을 병원으로 빨리 데려가요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'angel',
    meaning: '천사',
    hint: '날개가 있고 하늘에서 내려온다고 해요.',
    category: '기타',
    difficulty: '쉬움',
  ),
  Word(
    word: 'ant',
    meaning: '개미',
    hint: '작고 부지런히 일하는 곤충이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'anvil',
    meaning: '모루',
    hint: '대장장이가 사용하는 단단한 금속 도구예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'apple',
    meaning: '사과',
    hint: '빨갛거나 초록색이고 과일이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'arm',
    meaning: '팔',
    hint: '손이 연결된 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'asparagus',
    meaning: '아스파라거스',
    hint: '길쭉한 채소로 요리에 쓰여요.',
    category: '음식',
    difficulty: '어려움',
  ),
  Word(
    word: 'axe',
    meaning: '도끼',
    hint: '나무를 자르는데 쓰는 도구예요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'backpack',
    meaning: '배낭',
    hint: '등에 메고 다니는 가방이에요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'banana',
    meaning: '바나나',
    hint: '노란색이고 껍질을 벗겨 먹어요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bandage',
    meaning: '반창고',
    hint: '상처를 보호하기 위해 붙이는 물건이에요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'barn',
    meaning: '헛간',
    hint: '농장에서 짐승이나 물건을 보관하는 곳이에요.',
    category: '장소/건물',
    difficulty: '보통',
  ),
  Word(
    word: 'baseball',
    meaning: '야구',
    hint: '공을 던지고 치며 즐기는 스포츠예요.',
    category: '스포츠',
    difficulty: '쉬움',
  ),
  Word(
    word: 'basket',
    meaning: '바구니',
    hint: '물건을 담는 데 쓰는 그릇이에요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'basketball',
    meaning: '농구',
    hint: '공을 던져서 링에 넣는 스포츠예요.',
    category: '스포츠',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bat',
    meaning: '박쥐',
    hint: '밤에 활동하며 날 수 있는 포유류예요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bathtub',
    meaning: '욕조',
    hint: '몸을 담그고 씻는 큰 그릇이에요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'beach',
    meaning: '해변',
    hint: '바다와 육지가 만나는 모래사장이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bear',
    meaning: '곰',
    hint: '덩치가 크고 털이 많은 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'beard',
    meaning: '수염',
    hint: '얼굴에 나는 털이에요.',
    category: '사람/신체',
    difficulty: '보통',
  ),
  Word(
    word: 'bed',
    meaning: '침대',
    hint: '잠을 자는 데 사용하는 가구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bee',
    meaning: '벌',
    hint: '꽃에서 꿀을 모으고 날아다니는 곤충이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'belt',
    meaning: '벨트',
    hint: '바지를 고정하거나 허리를 감싸는 물건이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bench',
    meaning: '벤치',
    hint: '공원이나 길가에서 앉을 수 있는 긴 의자예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bicycle',
    meaning: '자전거',
    hint: '페달을 밟아 움직이는 두 바퀴 탈것이에요.',
    category: '교통수단',
    difficulty: '쉬움',
  ),
  Word(
    word: 'binoculars',
    meaning: '망원경',
    hint: '멀리 있는 것을 더 가까이 볼 수 있게 해주는 도구예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'bird',
    meaning: '새',
    hint: '날개가 있고 하늘을 나는 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'blackberry',
    meaning: '블랙베리',
    hint: '검은색 작은 열매로 맛이 달콤해요.',
    category: '음식',
    difficulty: '어려움',
  ),
  Word(
    word: 'blueberry',
    meaning: '블루베리',
    hint: '파란색 작은 열매로 건강에 좋아요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'book',
    meaning: '책',
    hint: '읽고 배울 수 있는 글이 적힌 물건이에요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'boomerang',
    meaning: '부메랑',
    hint: '던지면 다시 돌아오는 도구예요.',
    category: '스포츠',
    difficulty: '어려움',
  ),
  Word(
    word: 'bottlecap',
    meaning: '병뚜껑',
    hint: '병을 닫는 데 사용하는 작은 뚜껑이에요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'bowtie',
    meaning: '나비넥타이',
    hint: '정장에 매는 리본 모양의 넥타이예요.',
    category: '의류/패션',
    difficulty: '어려움',
  ),
  Word(
    word: 'bracelet',
    meaning: '팔찌',
    hint: '손목에 차는 장식품이에요.',
    category: '의류/패션',
    difficulty: '보통',
  ),
  Word(
    word: 'brain',
    meaning: '뇌',
    hint: '생각하고 몸을 조종하는 신체 기관이에요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bread',
    meaning: '빵',
    hint: '밀가루로 만들어 구운 음식이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bridge',
    meaning: '다리',
    hint: '몸을 지탱하고 걷는 데 사용하는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'broccoli',
    meaning: '브로콜리',
    hint: '초록색 채소로 나무처럼 생겼어요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'broom',
    meaning: '빗자루',
    hint: '바닥을 쓸고 청소할 때 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'bucket',
    meaning: '양동이',
    hint: '물이나 물건을 담는 데 사용하는 통이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bulldozer',
    meaning: '불도저',
    hint: '땅을 밀거나 평평하게 만드는 중장비예요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'bus',
    meaning: '버스',
    hint: '여러 사람이 함께 탈 수 있는 큰 차량이에요.',
    category: '교통수단',
    difficulty: '쉬움',
  ),
  Word(
    word: 'bush',
    meaning: '덤불',
    hint: '나무나 풀이 빽빽하게 모여 있는 곳이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'butterfly',
    meaning: '나비',
    hint: '날개가 아름다운 곤충이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cactus',
    meaning: '선인장',
    hint: '가시가 많고 물을 저장하는 식물이에요.',
    category: '자연/식물',
    difficulty: '어려움',
  ),
  Word(
    word: 'cake',
    meaning: '케이크',
    hint: '생일이나 특별한 날에 먹는 달콤한 디저트예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'calculator',
    meaning: '계산기',
    hint: '숫자를 더하거나 곱하는 데 사용하는 도구예요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'calendar',
    meaning: '달력',
    hint: '날짜와 요일을 확인할 수 있는 도구예요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'camel',
    meaning: '낙타',
    hint: '등에 혹이 있고 사막에서 잘 사는 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'camera',
    meaning: '카메라',
    hint: '사진을 찍는 데 사용하는 기계예요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'camouflage',
    meaning: '위장무늬',
    hint: '주변 환경과 섞이도록 디자인된 무늬예요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'campfire',
    meaning: '모닥불',
    hint: '야외에서 불을 피워 따뜻하게 하거나 요리할 때 사용해요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'candle',
    meaning: '촛불',
    hint: '어두운 곳을 밝히는 작은 불이에요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'cannon',
    meaning: '대포',
    hint: '포탄을 발사하는 큰 무기예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'canoe',
    meaning: '카누',
    hint: '물 위에서 노를 저어 움직이는 작은 배예요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'car',
    meaning: '자동차',
    hint: '바퀴가 달리고 엔진으로 움직이는 탈것이에요.',
    category: '교통수단',
    difficulty: '쉬움',
  ),
  Word(
    word: 'carrot',
    meaning: '당근',
    hint: '주황색이고 토끼가 좋아하는 채소예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'castle',
    meaning: '성',
    hint: '왕과 왕비가 사는 큰 건축물이거나 요새예요.',
    category: '장소/건물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cat',
    meaning: '고양이',
    hint: '야옹하고 울며 털이 부드러운 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cello',
    meaning: '첼로',
    hint: '크기가 큰 현악기로 낮은 음을 내는 악기예요.',
    category: '악기',
    difficulty: '보통',
  ),
  Word(
    word: 'chair',
    meaning: '의자',
    hint: '앉는 데 사용하는 가구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'chandelier',
    meaning: '샹들리에',
    hint: '천장에 매달려 빛을 내는 화려한 조명이에요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'church',
    meaning: '교회',
    hint: '사람들이 예배를 드리는 종교적인 건물이예요.',
    category: '장소/건물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'circle',
    meaning: '원',
    hint: '끝이 없이 둥글게 이어진 모양이에요.',
    category: '기타',
    difficulty: '쉬움',
  ),
  Word(
    word: 'clarinet',
    meaning: '클라리넷',
    hint: '목관악기로 부드럽고 맑은 소리를 내는 악기예요.',
    category: '악기',
    difficulty: '어려움',
  ),
  Word(
    word: 'clock',
    meaning: '시계',
    hint: '시간을 알려주는 도구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cloud',
    meaning: '구름',
    hint: '하늘에 떠다니며 비를 내리기도 하는 흰색이나 회색 덩어리예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'compass',
    meaning: '나침반',
    hint: '방향을 알려주는 도구로, 북쪽을 가리켜요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'computer',
    meaning: '컴퓨터',
    hint: '정보를 처리하고 다양한 작업을 수행하는 전자기기예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cookie',
    meaning: '쿠키',
    hint: '달콤하고 바삭한 작은 과자예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cooler',
    meaning: '쿨러',
    hint: '음료나 음식을 시원하게 유지하는 용기예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'couch',
    meaning: '소파',
    hint: '여러 사람이 앉을 수 있는 푹신한 가구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cow',
    meaning: '소',
    hint: '젖을 생산하고 풀을 먹는 농장 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'crab',
    meaning: '게',
    hint: '바닷가에서 볼 수 있는 집게발이 있는 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'crayons',
    meaning: '크레용',
    hint: '그림을 그릴 때 사용하는 색깔이 있는 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'crocodile',
    meaning: '악어',
    hint: '강과 늪에서 사는 커다란 파충류 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'crown',
    meaning: '왕관',
    hint: '왕이나 여왕이 머리에 쓰는 장식품이에요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'cup',
    meaning: '컵',
    hint: '물이나 음료를 담아 마시는 그릇이에요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'diamond',
    meaning: '다이아몬드',
    hint: '매우 단단하고 반짝이는 보석이에요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'dishwasher',
    meaning: '식기세척기',
    hint: '접시와 그릇을 자동으로 씻어주는 기계예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'dog',
    meaning: '개',
    hint: '사람과 친근하며 짖는 소리를 내는 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'dolphin',
    meaning: '돌고래',
    hint: '바다에서 사는 똑똑하고 점프를 잘하는 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'donut',
    meaning: '도넛',
    hint: '구멍이 뚫린 둥근 모양의 달콤한 빵이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'door',
    meaning: '문',
    hint: '방이나 건물로 들어가는 입구를 닫거나 여는 구조예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'dragon',
    meaning: '용',
    hint: '날개와 비늘이 있는 상상의 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'dresser',
    meaning: '서랍장',
    hint: '물건을 보관할 수 있는 여러 칸으로 된 가구예요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'drill',
    meaning: '드릴',
    hint: '구멍을 뚫거나 나사를 조이는 데 사용하는 전동 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'drums',
    meaning: '드럼',
    hint: '손이나 막대로 치며 소리를 내는 타악기예요.',
    category: '악기',
    difficulty: '쉬움',
  ),
  Word(
    word: 'duck',
    meaning: '오리',
    hint: '물 위를 떠다니며 꽥꽥 우는 새예요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'dumbbell',
    meaning: '아령',
    hint: '손으로 들고 운동할 때 사용하는 무게 도구예요.',
    category: '스포츠',
    difficulty: '어려움',
  ),
  Word(
    word: 'ear',
    meaning: '귀',
    hint: '소리를 듣는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'elbow',
    meaning: '팔꿈치',
    hint: '팔의 중간 관절로 구부릴 수 있는 부위예요.',
    category: '사람/신체',
    difficulty: '보통',
  ),
  Word(
    word: 'elephant',
    meaning: '코끼리',
    hint: '큰 귀와 긴 코를 가진 육상 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'envelope',
    meaning: '봉투',
    hint: '편지나 물건을 넣어 전달하는 종이 포장이에요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'eraser',
    meaning: '지우개',
    hint: '연필로 쓴 글씨를 지울 때 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'eye',
    meaning: '눈',
    hint: '세상을 보고 색깔과 모양을 구별하는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'eyeglasses',
    meaning: '안경',
    hint: '시력을 돕거나 눈을 보호하는 데 사용하는 도구예요.',
    category: '의류/패션',
    difficulty: '어려움',
  ),
  Word(
    word: 'face',
    meaning: '얼굴',
    hint: '눈, 코, 입이 있는 신체의 앞부분이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'fan',
    meaning: '선풍기',
    hint: '바람을 만들어 시원하게 해주는 가전제품이에요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'feather',
    meaning: '깃털',
    hint: '새의 몸을 덮고 있는 가벼운 털이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'fence',
    meaning: '울타리',
    hint: '공간을 구분하거나 보호하기 위해 설치된 구조물이예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'finger',
    meaning: '손가락',
    hint: '손에 달린 다섯 개의 움직이는 부분이에요.',
    category: '사람/신체',
    difficulty: '보통',
  ),
  Word(
    word: 'fireplace',
    meaning: '벽난로',
    hint: '집 안에서 불을 피워 따뜻하게 하는 구조물이예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'firetruck',
    meaning: '소방차',
    hint: '화재를 진압하기 위해 출동하는 차량이에요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'fish',
    meaning: '물고기',
    hint: '물속에서 헤엄치며 사는 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'flamingo',
    meaning: '플라밍고',
    hint: '긴 다리와 분홍색 깃털을 가진 새예요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'flashlight',
    meaning: '손전등',
    hint: '어두운 곳을 밝히는 휴대용 조명이에요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'flower',
    meaning: '꽃',
    hint: '식물에서 피어나며 아름답고 향기가 나는 부분이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'foot',
    meaning: '발',
    hint: '걷거나 뛰는 데 사용하는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '보통',
  ),
  Word(
    word: 'fork',
    meaning: '포크',
    hint: '음식을 찍어 먹는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'frog',
    meaning: '개구리',
    hint: '물과 땅에서 살며 뛰어다니는 양서류 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'garden',
    meaning: '정원',
    hint: '꽃과 나무를 심어 가꾸는 야외 공간이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'giraffe',
    meaning: '기린',
    hint: '목이 길고 키가 큰 초식 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'goatee',
    meaning: '턱수염',
    hint: '턱에 나는 얼굴 털이에요.',
    category: '사람/신체',
    difficulty: '어려움',
  ),
  Word(
    word: 'grapes',
    meaning: '포도',
    hint: '작고 둥글며 달콤한 과일이에요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'grass',
    meaning: '풀',
    hint: '땅 위에 자라는 초록색 식물이예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'guitar',
    meaning: '기타',
    hint: '줄을 튕겨서 소리를 내는 악기예요.',
    category: '악기',
    difficulty: '쉬움',
  ),
  Word(
    word: 'hamburger',
    meaning: '햄버거',
    hint: '빵 사이에 고기와 채소를 넣은 음식이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'hammer',
    meaning: '망치',
    hint: '못을 박거나 물건을 두드리는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'hand',
    meaning: '손',
    hint: '물건을 잡거나 만지는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'harp',
    meaning: '하프',
    hint: '줄을 뜯어서 소리를 내는 삼각형 모양의 악기예요.',
    category: '악기',
    difficulty: '어려움',
  ),
  Word(
    word: 'hat',
    meaning: '모자',
    hint: '머리에 쓰는 장식품이나 보호용 물건이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'headphone',
    meaning: '헤드폰',
    hint: '귀에 착용해 음악이나 소리를 들을 수 있는 장치예요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'hedgehog',
    meaning: '고슴도치',
    hint: '가시로 덮인 몸을 가진 작은 동물이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'helicopter',
    meaning: '헬리콥터',
    hint: '프로펠러로 하늘을 나는 탈것이에요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'helmet',
    meaning: '헬멧',
    hint: '머리를 보호하기 위해 쓰는 안전 장비예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'hexagon',
    meaning: '육각형',
    hint: '여섯 개의 변과 꼭짓점을 가진 도형이에요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'horse',
    meaning: '말',
    hint: '달리고 사람을 태울 수 있는 큰 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'hospital',
    meaning: '병원',
    hint: '아픈 사람을 치료하는 곳이에요.',
    category: '장소/건물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'hourglass',
    meaning: '모래시계',
    hint: '모래가 흘러 시간을 측정하는 도구예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'house',
    meaning: '집',
    hint: '사람들이 사는 건물이에요.',
    category: '장소/건물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'hurricane',
    meaning: '허리케인',
    hint: '강한 바람과 비를 동반하는 거대한 폭풍이에요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'jacket',
    meaning: '재킷',
    hint: '추위를 막기 위해 입는 겉옷이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'jail',
    meaning: '감옥',
    hint: '죄를 지은 사람이 갇히는 장소예요.',
    category: '장소/건물',
    difficulty: '어려움',
  ),
  Word(
    word: 'kangaroo',
    meaning: '캥거루',
    hint: '뛰어다니고 주머니를 가진 호주 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'key',
    meaning: '열쇠',
    hint: '문이나 자물쇠를 열거나 잠그는 도구예요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'keyboard',
    meaning: '키보드',
    hint: '컴퓨터에서 글자를 입력하는 데 사용하는 도구예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'knee',
    meaning: '무릎',
    hint: '다리의 중간 관절로 구부릴 수 있는 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'knife',
    meaning: '칼',
    hint: '물건을 자르거나 썰 때 사용하는 날카로운 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'ladder',
    meaning: '사다리',
    hint: '높은 곳으로 올라갈 때 사용하는 계단 모양 도구예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'lantern',
    meaning: '랜턴',
    hint: '어두운 곳을 밝히는 휴대용 조명이에요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'laptop',
    meaning: '노트북',
    hint: '휴대할 수 있는 작은 컴퓨터예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'leaf',
    meaning: '나뭇잎',
    hint: '나무에서 자라며 초록색인 잎사귀예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'leg',
    meaning: '다리(신체)',
    hint: '걷거나 뛰는 데 사용하는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'lighter',
    meaning: '라이터',
    hint: '불을 붙이는 데 사용하는 작은 도구예요.',
    category: '장소/건물',
    difficulty: '보통',
  ),
  Word(
    word: 'lighthouse',
    meaning: '등대',
    hint: '바다 근처에서 빛으로 배를 안내하는 구조물이에요.',
    category: '장소/건물',
    difficulty: '어려움',
  ),
  Word(
    word: 'lightning',
    meaning: '번개',
    hint: '폭풍 중 하늘에서 빛이 번쩍이는 현상이에요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'line',
    meaning: '선',
    hint: '길게 이어진 직선 모양의 도형이에요.',
    category: '기타',
    difficulty: '쉬움',
  ),
  Word(
    word: 'lion',
    meaning: '사자',
    hint: '갈기가 있고 숲의 왕으로 불리는 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'lipstick',
    meaning: '립스틱',
    hint: '입술에 색깔을 바르는 화장품이에요.',
    category: '의류/패션',
    difficulty: '보통',
  ),
  Word(
    word: 'lobster',
    meaning: '바닷가재',
    hint: '바다에서 사는 딱딱한 껍질을 가진 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'lollipop',
    meaning: '롤리팝',
    hint: '막대기에 달린 달콤한 사탕이에요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'mailbox',
    meaning: '우체통',
    hint: '편지를 넣는 데 사용하는 상자예요.',
    category: '사물',
    difficulty: '보통',
  ),
  Word(
    word: 'map',
    meaning: '지도',
    hint: '지역과 길을 표시한 그림이에요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'marker',
    meaning: '마커',
    hint: '글씨를 쓰거나 표시할 때 사용하는 굵은 펜이에요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'matches',
    meaning: '성냥',
    hint: '불을 붙이는 데 사용하는 작은 나무 막대예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'megaphone',
    meaning: '확성기',
    hint: '소리를 크게 내는 데 사용하는 장치예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'mermaid',
    meaning: '인어',
    hint: '물고기 꼬리를 가진 상상의 생물이예요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'microphone',
    meaning: '마이크',
    hint: '소리를 증폭해주는 장치예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'microwave',
    meaning: '전자레인지',
    hint: '음식을 빠르게 데우거나 요리하는 전자기기예요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'monkey',
    meaning: '원숭이',
    hint: '나무를 잘 타고 장난꾸러기인 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'moon',
    meaning: '달',
    hint: '밤하늘에서 빛나는 둥근 천체예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'mosquito',
    meaning: '모기',
    hint: '사람의 피를 빨아먹는 작은 곤충이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'motorbike',
    meaning: '오토바이',
    hint: '바퀴 두 개로 빠르게 이동할 수 있는 탈것이에요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'mountain',
    meaning: '산',
    hint: '땅 위로 높이 솟아 있는 자연 지형이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'mouse',
    meaning: '쥐',
    hint: '작고 빠르게 움직이는 설치류 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'moustache',
    meaning: '콧수염',
    hint: '코 아래에 나는 얼굴 털이에요.',
    category: '사람/신체',
    difficulty: '어려움',
  ),
  Word(
    word: 'mouth',
    meaning: '입',
    hint: '말을 하고 음식을 먹는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'mug',
    meaning: '머그잔',
    hint: '커피나 차를 마실 때 사용하는 큰 잔이에요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'mushroom',
    meaning: '버섯',
    hint: '땅이나 나무에서 자라는 갓 모양의 식물이예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'nail',
    meaning: '못',
    hint: '물건을 고정할 때 사용하는 금속 핀이에요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'necklace',
    meaning: '목걸이',
    hint: '목에 걸어 장식하는 액세서리예요.',
    category: '의류/패션',
    difficulty: '보통',
  ),
  Word(
    word: 'nose',
    meaning: '코',
    hint: '냄새를 맡고 숨쉬는 신체 부위예요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'ocean',
    meaning: '바다',
    hint: '넓고 깊은 물로 이루어진 자연 지형이에요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'octagon',
    meaning: '팔각형',
    hint: '여덟 개의 변과 꼭짓점을 가진 도형이에요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'octopus',
    meaning: '문어',
    hint: '다리가 여덟 개이고 물속에서 사는 동물이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'onion',
    meaning: '양파',
    hint: '껍질을 벗기면 눈물이 나는 채소예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'oven',
    meaning: '오븐',
    hint: '음식을 굽거나 데우는 데 사용하는 가전제품이에요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'owl',
    meaning: '올빼미',
    hint: '밤에 활동하고 큰 눈을 가진 새예요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'paintbrush',
    meaning: '붓',
    hint: '그림을 그리거나 페인트칠할 때 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'panda',
    meaning: '판다',
    hint: '대나무를 먹고 흰색과 검은색 털을 가진 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'pants',
    meaning: '바지',
    hint: '다리에 입는 옷이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'parachute',
    meaning: '낙하산',
    hint: '하늘에서 천천히 내려올 때 사용하는 장비예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'parrot',
    meaning: '앵무새',
    hint: '말을 따라 할 수 있는 알록달록한 새예요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'passport',
    meaning: '여권',
    hint: '해외여행 시 신분을 증명하는 문서예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'peanuts',
    meaning: '땅콩',
    hint: '껍질 속에 들어 있는 작은 견과류예요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'pear',
    meaning: '배',
    hint: '물 위를 떠다니며 사람이나 물건을 운반하는 탈것이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'peas',
    meaning: '완두콩',
    hint: '초록색 작은 콩으로 껍질 안에 여러 개가 들어 있어요.',
    category: '음식',
    difficulty: '어려움',
  ),
  Word(
    word: 'pencil',
    meaning: '연필',
    hint: '글씨를 쓰거나 그림을 그릴 때 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'penguin',
    meaning: '펭귄',
    hint: '날지 못하지만 수영을 잘하는 새예요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'piano',
    meaning: '피아노',
    hint: '건반을 눌러 소리를 내는 악기예요.',
    category: '악기',
    difficulty: '쉬움',
  ),
  Word(
    word: 'pig',
    meaning: '돼지',
    hint: '코가 납작하고 꿀꿀 소리를 내는 농장 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'pillow',
    meaning: '베개',
    hint: '잠잘 때 머리를 올려놓는 부드러운 물건이에요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'pineapple',
    meaning: '파인애플',
    hint: '껍질이 딱딱하고 속이 달콤한 열대 과일이에요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'pizza',
    meaning: '피자',
    hint: '둥글고 위에 치즈와 토핑이 올라간 음식이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'pliers',
    meaning: '펜치',
    hint: '물건을 잡거나 자르는 데 사용하는 공구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'pond',
    meaning: '연못',
    hint: '물고기나 식물이 사는 작은 물웅덩이예요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'pool',
    meaning: '수영장',
    hint: '사람들이 수영할 수 있도록 만든 인공 물탱크예요.',
    category: '장소/건물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'popsicle',
    meaning: '아이스바',
    hint: '막대기에 꽂힌 얼린 디저트예요.',
    category: '음식',
    difficulty: '어려움',
  ),
  Word(
    word: 'postcard',
    meaning: '엽서',
    hint: '그림과 글로 메시지를 전달하는 카드예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'potato',
    meaning: '감자',
    hint: '땅속에서 자라는 갈색 껍질의 채소예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'purse',
    meaning: '지갑',
    hint: '돈이나 카드를 보관하는 작은 가죽 물건이에요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'rabbit',
    meaning: '토끼',
    hint: '귀가 길고 뛰어다니며 당근을 좋아하는 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'raccoon',
    meaning: '라쿤',
    hint: '얼굴에 검은 줄무늬가 있는 귀여운 동물이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'radio',
    meaning: '라디오',
    hint: '음악과 뉴스를 들을 수 있는 전자 기기예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'rain',
    meaning: '비',
    hint: '하늘에서 떨어지는 물방울이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'rainbow',
    meaning: '무지개',
    hint: '비 온 뒤 하늘에 나타나는 일곱 가지 색의 띠예요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'rake',
    meaning: '갈퀴',
    hint: '낙엽이나 흙을 긁어모으는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'rhinoceros',
    meaning: '코뿔소',
    hint: '코에 뿔이 달린 큰 육상 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'rifle',
    meaning: '소총',
    hint: '총알을 발사하는 긴 무기예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'river',
    meaning: '강',
    hint: '땅 위를 흐르는 긴 물줄기예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'rollerskate',
    meaning: '롤러스케이트',
    hint: '바퀴가 달린 신발로 타고 다니는 스포츠 장비예요.',
    category: '스포츠',
    difficulty: '보통',
  ),
  Word(
    word: 'sailboat',
    meaning: '돛단배',
    hint: '돛을 사용해 바람으로 움직이는 작은 배예요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'sandwich',
    meaning: '샌드위치',
    hint: '빵 사이에 여러 재료를 넣어 만든 음식이에요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'saw',
    meaning: '톱',
    hint: '나무를 자르는 데 사용하는 날카로운 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'saxophone',
    meaning: '색소폰',
    hint: '금속으로 만들어진 관악기로 재즈 음악에 많이 쓰여요.',
    category: '악기',
    difficulty: '어려움',
  ),
  Word(
    word: 'scissors',
    meaning: '가위',
    hint: '종이나 천을 자르는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'scorpion',
    meaning: '전갈',
    hint: '꼬리에 독침이 있는 사막에서 사는 곤충이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'screwdriver',
    meaning: '드라이버',
    hint: '나사를 돌려 조이는 데 사용하는 공구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'shark',
    meaning: '상어',
    hint: '바다에서 사는 날카로운 이빨을 가진 포식자예요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'sheep',
    meaning: '양',
    hint: '털이 많고 풀을 먹는 농장 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'shoe',
    meaning: '신발',
    hint: '발을 보호하고 편하게 걷게 해주는 물건이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'shorts',
    meaning: '반바지',
    hint: '무릎 위까지 오는 짧은 바지예요.',
    category: '의류/패션',
    difficulty: '어려움',
  ),
  Word(
    word: 'shovel',
    meaning: '삽',
    hint: '흙이나 모래를 퍼 올리는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'sink',
    meaning: '싱크대',
    hint: '설거지를 하거나 물을 사용하는 주방 기구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'skateboard',
    meaning: '스케이트보드',
    hint: '바퀴가 달린 판 위에 올라타서 타고 다니는 스포츠 장비예요.',
    category: '스포츠',
    difficulty: '보통',
  ),
  Word(
    word: 'skull',
    meaning: '해골',
    hint: '사람이나 동물의 뼈대 중 머리 부분이에요.',
    category: '사람/신체',
    difficulty: '어려움',
  ),
  Word(
    word: 'skyscraper',
    meaning: '마천루',
    hint: '도시에서 매우 높은 건물이예요.',
    category: '장소/건물',
    difficulty: '보통',
  ),
  Word(
    word: 'snail',
    meaning: '달팽이',
    hint: '껍질을 등에 지고 느리게 움직이는 작은 동물이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'snake',
    meaning: '뱀',
    hint: '다리가 없고 기어다니며 길쭉한 몸을 가진 파충류예요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'snorkel',
    meaning: '스노클',
    hint: '물속에서 숨 쉴 때 사용하는 호흡 장치예요.',
    category: '스포츠',
    difficulty: '어려움',
  ),
  Word(
    word: 'snowflake',
    meaning: '눈송이',
    hint: '겨울에 하늘에서 떨어지는 얼음 결정체예요.',
    category: '자연/식물',
    difficulty: '어려움',
  ),
  Word(
    word: 'snowman',
    meaning: '눈사람',
    hint: '눈을 뭉쳐서 만든 사람 모양의 조각이에요.',
    category: '자연/식물',
    difficulty: '어려움',
  ),
  Word(
    word: 'socks',
    meaning: '양말',
    hint: '발에 신는 부드러운 옷이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'speedboat',
    meaning: '모터보트',
    hint: '엔진으로 움직이는 작은 배예요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'spider',
    meaning: '거미',
    hint: '다리가 여덟 개이고 거미줄을 만드는 곤충이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'spoon',
    meaning: '숟가락',
    hint: '음식을 떠먹는 데 사용하는 도구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'spreadsheet',
    meaning: '스프레드시트',
    hint: '데이터를 표로 정리하고 계산할 수 있는 프로그램이에요.',
    category: '기타',
    difficulty: '보통',
  ),
  Word(
    word: 'square',
    meaning: '정사각형',
    hint: '네 변의 길이가 같고 네 각이 직각인 도형이에요.',
    category: '기타',
    difficulty: '쉬움',
  ),
  Word(
    word: 'squiggle',
    meaning: '구불구불한 선',
    hint: '곧지 않고 휘어져 있는 선 모양이에요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'squirrel',
    meaning: '다람쥐',
    hint: '나무 위를 뛰어다니며 도토리를 먹는 작은 동물이에요.',
    category: '동물',
    difficulty: '어려움',
  ),
  Word(
    word: 'stairs',
    meaning: '계단',
    hint: '위아래로 이동할 때 사용하는 층층이 놓인 구조예요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'star',
    meaning: '별',
    hint: '밤하늘에서 반짝이는 천체예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'steak',
    meaning: '스테이크',
    hint: '고기를 두껍게 썰어 구운 요리예요.',
    category: '음식',
    difficulty: '쉬움',
  ),
  Word(
    word: 'stereo',
    meaning: '스테레오',
    hint: '음악이나 소리를 재생하는 오디오 장치예요.',
    category: '기타',
    difficulty: '어려움',
  ),
  Word(
    word: 'strawberry',
    meaning: '딸기',
    hint: '빨갛고 달콤한 작은 과일이에요.',
    category: '음식',
    difficulty: '보통',
  ),
  Word(
    word: 'streetlight',
    meaning: '가로등',
    hint: '길거리를 밝히는 데 사용하는 높은 조명이에요.',
    category: '사물',
    difficulty: '어려움',
  ),
  Word(
    word: 'submarine',
    meaning: '잠수함',
    hint: '물속에서 움직이는 군사용 또는 탐사용 배예요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'suitcase',
    meaning: '여행가방',
    hint: '여행 시 옷이나 물건을 담는 큰 가방이에요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'sun',
    meaning: '해',
    hint: '낮 동안 하늘에서 빛과 열을 내는 천체예요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'swan',
    meaning: '백조',
    hint: '목이 길고 우아하게 헤엄치는 새예요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'sweater',
    meaning: '스웨터',
    hint: '추울 때 입는 두꺼운 니트 옷이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'sword',
    meaning: '칼',
    hint: '음식을 자르거나 써는 데 사용하는 날카로운 도구예요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'syringe',
    meaning: '주사기',
    hint: '약물을 주입하거나 뽑아내는 데 사용하는 의료 도구예요.',
    category: '문구/도구',
    difficulty: '어려움',
  ),
  Word(
    word: 'table',
    meaning: '식탁',
    hint: '음식을 먹을 때 사용하는 테이블이에요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'teapot',
    meaning: '찻주전자',
    hint: '차를 끓이거나 따르는 데 사용하는 주전자예요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'telephone',
    meaning: '전화기',
    hint: '멀리 있는 사람과 대화할 수 있는 통신 기기예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'television',
    meaning: '텔레비전',
    hint: '화면으로 방송을 볼 수 있는 전자 기기예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'tent',
    meaning: '텐트',
    hint: '야외에서 잠잘 때 사용하는 천으로 된 임시 집이에요.',
    category: '가전/가구',
    difficulty: '보통',
  ),
  Word(
    word: 'tiger',
    meaning: '호랑이',
    hint: '줄무늬가 있고 숲 속에서 사는 큰 고양잇과 동물이에요.',
    category: '동물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'toaster',
    meaning: '토스터',
    hint: '빵을 구워주는 주방 가전제품이에요.',
    category: '가전/가구',
    difficulty: '어려움',
  ),
  Word(
    word: 'toe',
    meaning: '발가락',
    hint: '발 끝에 있는 다섯 개의 작은 부분이에요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'toilet',
    meaning: '변기',
    hint: '화장실에서 용변을 볼 때 사용하는 기구예요.',
    category: '가전/가구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'tooth',
    meaning: '이',
    hint: '머리카락에 사는 작은 곤충이에요.',
    category: '사람/신체',
    difficulty: '쉬움',
  ),
  Word(
    word: 'toothbrush',
    meaning: '칫솔',
    hint: '이를 닦는 데 사용하는 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'toothpaste',
    meaning: '치약',
    hint: '칫솔에 짜서 이를 깨끗하게 하는 데 사용하는 물질이에요.',
    category: '문구/도구',
    difficulty: '보통',
  ),
  Word(
    word: 'tornado',
    meaning: '토네이도',
    hint: '강한 바람이 소용돌이치는 자연재해예요.',
    category: '자연/식물',
    difficulty: '보통',
  ),
  Word(
    word: 'tractor',
    meaning: '트랙터',
    hint: '농장에서 일할 때 사용하는 큰 기계예요.',
    category: '교통수단',
    difficulty: '어려움',
  ),
  Word(
    word: 'train',
    meaning: '기차',
    hint: '여러 칸으로 연결되어 철로 위를 달리는 탈것이에요.',
    category: '교통수단',
    difficulty: '쉬움',
  ),
  Word(
    word: 'tree',
    meaning: '나무',
    hint: '땅에서 자라고 가지와 잎이 있는 식물이에요.',
    category: '자연/식물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'triangle',
    meaning: '삼각형',
    hint: '세 개의 변과 꼭짓점을 가진 도형이에요.',
    category: '기타',
    difficulty: '보통',
  ),
  Word(
    word: 'trombone',
    meaning: '트롬본',
    hint: '길이를 늘려서 소리를 내는 금관악기예요.',
    category: '악기',
    difficulty: '어려움',
  ),
  Word(
    word: 'truck',
    meaning: '트럭',
    hint: '짐을 운반하는 데 사용되는 큰 차량이에요.',
    category: '교통수단',
    difficulty: '쉬움',
  ),
  Word(
    word: 'trumpet',
    meaning: '트럼펫',
    hint: '입으로 불어 소리를 내는 금관악기예요.',
    category: '악기',
    difficulty: '보통',
  ),
  Word(
    word: 't-shirt',
    meaning: '티셔츠',
    hint: '짧은 소매가 있는 편안한 상의 옷이에요.',
    category: '의류/패션',
    difficulty: '쉬움',
  ),
  Word(
    word: 'umbrella',
    meaning: '우산',
    hint: '비를 막기 위해 사용하는 접히는 도구예요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'underwear',
    meaning: '속옷',
    hint: '겉옷 안에 입는 옷이에요.',
    category: '의류/패션',
    difficulty: '보통',
  ),
  Word(
    word: 'van',
    meaning: '밴',
    hint: '여러 사람이 탈 수 있는 중간 크기의 차량이에요.',
    category: '교통수단',
    difficulty: '보통',
  ),
  Word(
    word: 'vase',
    meaning: '꽃병',
    hint: '꽃을 담아 장식하는 데 사용하는 용기예요.',
    category: '사물',
    difficulty: '쉬움',
  ),
  Word(
    word: 'violin',
    meaning: '바이올린',
    hint: '활로 줄을 긁어서 소리를 내는 현악기예요.',
    category: '악기',
    difficulty: '쉬움',
  ),
  Word(
    word: 'watermelon',
    meaning: '수박',
    hint: '껍질은 녹색이고 속은 빨간색이며 씨가 있는 과일이에요.',
    category: '음식',
    difficulty: '어려움',
  ),
  Word(
    word: 'waterslide',
    meaning: '워터슬라이드',
    hint: '물 위를 미끄러져 내려오는 놀이 시설이에요.',
    category: '장소/건물',
    difficulty: '어려움',
  ),
  Word(
    word: 'whale',
    meaning: '고래',
    hint: '바다에서 사는 가장 큰 동물이자 포유류예요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'wheel',
    meaning: '바퀴',
    hint: '둥글고 굴러가는 탈것이나 기계의 부품이에요.',
    category: '문구/도구',
    difficulty: '쉬움',
  ),
  Word(
    word: 'windmill',
    meaning: '풍차',
    hint: '바람의 힘으로 회전하며 에너지를 만드는 장치예요.',
    category: '장소/건물',
    difficulty: '어려움',
  ),
  Word(
    word: 'wristwatch',
    meaning: '손목시계',
    hint: '손목에 차고 시간을 확인할 수 있는 시계예요.',
    category: '의류/패션',
    difficulty: '보통',
  ),
  Word(
    word: 'zebra',
    meaning: '얼룩말',
    hint: '흰색과 검은색 줄무늬가 있는 초식 동물이에요.',
    category: '동물',
    difficulty: '보통',
  ),
  Word(
    word: 'zigzag',
    meaning: '지그재그',
    hint: '직선이 아닌 왔다 갔다 휘어진 선 모양이에요.',
    category: '기타',
    difficulty: '어려움',
  ),
];

/// 난이도에 따라 단어 필터링하는 함수
List<Word> filterWordsByDifficulty(String difficulty) {
  if (difficulty == '쉬움') {
    return allWords.where((word) => word.difficulty == '쉬움').toList();
  } else if (difficulty == '보통') {
    return allWords
        .where((word) => word.difficulty == '쉬움' || word.difficulty == '보통')
        .toList();
  } else {
    // 어려움 난이도는 모든 단어 포함
    return List.from(allWords);
  }
}
